include:
  - project: olp/onesearch/infrastructure/gitlabci-utils
    file: variables_from_vault.yml
    ref: master

variables:
  DOCKER_DRIVER: overlay2
  CONTAINER_NAME: onesearch-demo
  GIT_SUBMODULE_STRATEGY: recursive
  ARTIFACTORY_URL: docker-local.artifactory.in.here.com
  VAULT_SERVER_URL: https://vault.hcs.aws.in.here.com/
  VAULT_AUTH_ROLE: gitlab-default
  VAULT_AUTH_PATH: gitlab-jwt

image: docker:stable
services:
  - docker:dind

.artfactory_login: &artfactory_login
- STATUS=0 ;for i in 1 2 3 4 5; do
      (echo "$ARTIFACTORY_PASS" | base64 -d | docker login -u $ARTIFACTORY_USER --password-stdin $ARTIFACTORY_URL) && break || STATUS=$(echo $?; sleep 15);
    done ; [ $STATUS -ne 0 ] && exit 1

stages:
  - test
  - build
  - push

coverage:
  stage: test
  image: "hcr.data.here.com/public_mirror/python:3.8-slim"
  script:
    - pip install -e .
    - pip install -r requirements_dev.txt
    - coverage run --source src -m pytest
    - coverage report -m
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'

test36:
  stage: test
  image: "hcr.data.here.com/public_mirror/python:3.6-slim"
  script:
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pytest

test37:
  stage: test
  image: "hcr.data.here.com/public_mirror/python:3.7.9-slim"
  script:
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pytest

#test38:
#  stage: test
#  image: "hcr.data.here.com/public_mirror/python:3.8-slim"
#  script:
#    - pip install -e .
#    - pip install -r requirements_dev.txt
#    - pytest

#test39:
#  stage: test
#  image: "hcr.data.here.com/public_mirror/python:3.9-slim"
#  script:
#    - pip install -e .
#    - pip install -r requirements_dev.txt
#    - pytest

test310:
  stage: test
  image: "hcr.data.here.com/public_mirror/python:3.10-alpine"
  script:
    - pip install -e .
    - pip install -r requirements_dev.txt
    - pytest

build:
  stage: build
  script:
    - *artfactory_login
    - apk add --update --no-cache sudo bash py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make
    - ln -sf python /usr/bin/python
    - pip install --no-cache --upgrade pip setuptools
    - PATH=/home/search:/home/search/.local/bin:$PATH
    - pip install jupyter-repo2docker --extra-index-url https://artifactory.in.here.com/artifactory/api/pypi/onesearch-pypi/simple
    - adduser -h /home search -S -D -u 1999
    - /usr/bin/jupyter-repo2docker --no-run --image-name ${CONTAINER_NAME} --user-id 1999 --user-name search .
    # The following should be in a follow-up push stage
    - SEARCH_DEMO_VERSION=$(cut -d\' -f2 src/here_search/__init__.py)
    - DEPLOYMENT_ID=${CI_PROJECT_NAME}-${SEARCH_DEMO_VERSION}-$CI_COMMIT_REF_NAME-${CI_COMMIT_SHORT_SHA}
    - docker tag ${CONTAINER_NAME} ${ARTIFACTORY_URL}/${CONTAINER_NAME}:$DEPLOYMENT_ID
    - docker tag ${CONTAINER_NAME} ${ARTIFACTORY_URL}/${CONTAINER_NAME}:latest
    - docker push ${ARTIFACTORY_URL}/${CONTAINER_NAME}:latest
