include:
  - project: olp/onesearch/infrastructure/gitlabci-utils
    file: variables_from_vault.yml
    ref: master

image: docker:stable

stages:
  - build

before_script:
  - apk add --update --no-cache sudo bash py-pip python3-dev libffi-dev openssl-dev gcc libc-dev make 
  - ln -sf python /usr/bin/python
  - pip3 install --no-cache --upgrade pip setuptools
  
build:
  stage: build  
  services:
    - docker:dind
  script:
    - PATH=/home/search:/home/search/.local/bin:$PATH
    - pip3 install jupyter-repo2docker
    - adduser -h /home search -S -D -u 1999
    - /usr/bin/jupyter-repo2docker --no-run --image-name search-demo-repo2docker --user-id 1999 --user-name search .
    - docker save search-demo-repo2docker:latest | gzip > search-demo-repo2docker.tgz
  artifacts:
    paths:
      - search-demo-repo2docker.tgz
